# Generated by Django 3.0.1 on 2020-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('D_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photo')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Destination_Info',
            },
        ),
    ]
