# Generated by Django 3.0.1 on 2020-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_destination_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1),
        ),
    ]
