# Generated by Django 3.0.1 on 2020-02-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200204_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
