# Generated by Django 3.0.1 on 2020-02-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200205_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
