# Generated by Django 3.0.1 on 2020-02-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200206_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
    ]
