# Generated by Django 3.0.1 on 2020-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20200206_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('G_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/photo')),
                ('Number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'our_gallery',
            },
        ),
    ]
